# Generated by Django 5.2.7 on 2025-11-29 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_order", "🎉 Новый заказ"),
                            ("order_status_changed", "📦 Статус заказа изменен"),
                            ("new_message", "💬 Новое сообщение"),
                            ("product_favorited", "❤️ Товар добавлен в избранное"),
                            ("system", "🔔 Системное уведомление"),
                            ("order_cancelled", "❌ Заказ отменен"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "related_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("related_content_type", models.CharField(blank=True, max_length=100)),
                ("action_url", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
