# Generated by Django 5.2.7 on 2025-11-29 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранные товары",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=60,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Название должно содержать только кириллические символы, цифры и пробелы",
                                regex="^[а-яА-ЯёЁ0-9\\s\\-\\!\\.\\(\\)]+$",
                            )
                        ],
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=300,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Описание должно содержать только кириллические символы, цифры и знаки препинания",
                                regex="^[а-яА-ЯёЁ0-9\\s\\-\\!\\.\\(\\)\\,\\:\\;]+$",
                            )
                        ],
                        verbose_name="Описание",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="Цена должна быть не менее 1 рубля"
                            ),
                            django.core.validators.MaxValueValidator(
                                5000000,
                                message="Цена не может превышать 5,000,000 рублей",
                            ),
                        ],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный"),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False, verbose_name="Одобрено модератором"
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="product_images/", verbose_name="Изображение"
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False, verbose_name="Основное изображение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение товара",
                "verbose_name_plural": "Изображения товаров",
            },
        ),
    ]
