# Generated by Django 5.2.7 on 2025-11-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_approved",
            field=models.BooleanField(
                default=False, verbose_name="Одобрено модератором"
            ),
        ),
    ]
